add script python
shayani/randomness pull request #1
Opened 2022-12-26 04:30 UTC by Wellyson-Lopes

2022-12-26 04:32 UTC, Wellyson-Lopes commented
segue script em python para testes de random

2022-12-26 08:48 UTC, shayani requested changes

2022-12-26 08:48 UTC, shayani commented on python.py
> +import random
Depois do `import`, sempre tem uma linha em branco.

2022-12-26 08:48 UTC, shayani commented on python.py
> +for i in range(0,1000000):
Extraia o tamanho do teste para uma variável `test_size`. 
O Python (assim como outras) aceita que escrevamos número grandes com `_` para facilitar a leitura. Assim, `1000000` fica `1_000_000`.

2022-12-26 08:48 UTC, shayani commented on python.py
> +porcentagem_zeros = zeros / 1000000 *100
Fixe o máximo de casas decimais da porcentagem para 3 (como foi feito nos scripts das outras linguagens). 
Para calcular a porcentagem, use a variável to `test_size`, e não um número fixo.

2022-12-26 08:48 UTC, shayani commented on python.py
> +print(f"Numeros 0:{zeros}, \nNumeros 1:{ones}")
O texto de saída deve estar em ingles (afinal, este repositório é publico ;).
Use o mesmo texto dos outros scripts para manter a consistência com as outras linguagens.

2022-12-26 08:48 UTC, shayani commented on python.py
> +print(f"A porcentagem de ones é: {porcentagem_ones}%")
Adicine uma linha em branco no final do arquivo. Tem uma configuração no VSCode que automaticamente coloca essa linha em branco, caso não exista.

2022-12-26 08:49 UTC, shayani commented
A lógica está boa e o script faz o que esperávamos ;) 👍

2022-12-27 08:01 UTC, shayani requested changes
Unifique os commits em 1 só apenas

2022-12-27 08:01 UTC, shayani commented on python.py
> +for i in range(0,test_size):
Sempre de um espaço apos a vírgula

2022-12-28 11:44 UTC, closed without merging